# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{warekky}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Takeshi AKIMA"]
  s.date = %q{2010-06-10}
  s.description = %q{Japanese Era(年号) library and Time, Date, DateTime extensions.}
  s.email = %q{akm2000@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/warekky.rb",
     "lib/warekky/core_ext.rb",
     "lib/warekky/era.rb",
     "lib/warekky/era_group.rb",
     "lib/warekky/ja.rb",
     "spec/core_ext/with_date_spec.rb",
     "spec/core_ext/with_date_time_spec.rb",
     "spec/core_ext/with_time_spec.rb",
     "spec/ja/with_date_spec.rb",
     "spec/ja/with_date_time_spec.rb",
     "spec/ja/with_time_spec.rb",
     "spec/rcov.opts",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/warekky/era_group_spec.rb",
     "spec/warekky/era_spec.rb",
     "spec/warekky_spec.rb",
     "warekky.gemspec"
  ]
  s.homepage = %q{http://github.com/akm/warekky}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Japanese Era(年号) library and Time, Date, DateTime extensions.}
  s.test_files = [
    "spec/core_ext/with_date_spec.rb",
     "spec/core_ext/with_date_time_spec.rb",
     "spec/core_ext/with_time_spec.rb",
     "spec/ja/with_date_spec.rb",
     "spec/ja/with_date_time_spec.rb",
     "spec/ja/with_time_spec.rb",
     "spec/spec_helper.rb",
     "spec/warekky/era_group_spec.rb",
     "spec/warekky/era_spec.rb",
     "spec/warekky_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

